[package]
edition = "2018"
name = "wasm"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.42"
console_error_panic_hook = "0.1.6"
next-swc = {version = "0.0.0", path = "../core"}
once_cell = "1.3.1"
parking_lot_core = "=0.8.0"
path-clean = "0.1"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
swc = { version = "0.181.0", features = ["plugin"] }
swc_common = { version = "0.18.5", features = ["concurrent", "sourcemap"] }
swc_ecmascript = { version = "0.157.0", features = ["codegen", "minifier", "optimization", "parser", "react", "transforms", "typescript", "utils", "visit"] }
tracing = { version = "0.1.32", features = ["release_max_level_off"] }
wasm-bindgen = {version = "0.2", features = ["serde-serialize"]}
wasm-bindgen-futures = "0.4.8"

# The following are only declared to enable features of transitive dependencies that we need in order to use the plugin feature of swc.
# This abuses the additive nature of Rust features and is a hack, actually swc should make sure all necessary features for plugins are enabled.

getrandom = { version = "0.2.6", features = ["js"] }
wasmer-wasi = { version = "2.2.1", default-features = false, features = ["js-default"] }
swc_plugin_runner = { version = "0.55.0", default-features = false, features = ["memory_cache"] }
