version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: shared-cache-with-redis
    ports:
      - '6379:6379'
      - '8001:8001'
    restart: unless-stopped
