[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>", "OJ Kwon <kwon.ohjoong@gmail.com>"]
name = "swc_relay_transform"
description = "SWC custom transform for relay.dev"
license = "Apache-2.0"
version = "0.1.0"
edition = "2018"

repository = "https://github.com/vercel/next.js.git"

[dependencies]
swc_atoms = "0.2.11"
swc_common = "0.18.2"
swc_ecmascript = "0.157.0"
serde = "1"
serde_json = "1"
regex = "1.5"
once_cell = "1.8.0"