[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>", "OJ Kwon <kwon.ohjoong@gmail.com>"]
name = "swc_relay_transform"
description = "SWC custom transform for relay.dev"
license = "Apache-2.0"
version = "0.1.0"
edition = "2018"

repository = "https://github.com/vercel/next.js.git"

[features]
plugin = ["swc_plugin"]

[dependencies]
swc_atoms = "0.2.12"
swc_common = "0.18.9"
swc_ecmascript = {version = "0.164.0", features = ["utils", "visit"]}
serde = "1"
serde_json = "1"
regex = "1.5"
once_cell = "1.8.0"
swc_plugin = {version = "0.63.0", optional = true }

[dev-dependencies]
swc_ecma_transforms_testing = "0.91.0"
testing = "0.20.0"
