pool:
  vmImage: 'vs2017-win2016'

strategy:
  maxParallel: 10
  matrix:
    node-10-2:
      group: 1
      node_version: ^10.10.0
    node-10:
      group: 2
      node_version: ^10.10.0
    node-8:
      group: 1
      node_version: ^8.12.0

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: 'Install Node.js'

  - script: |
      echo $(group)
    displayName: 'Echo group'

  - script: |
      yarn install
    displayName: 'Install dependencies'

  - script: |
      yarn check
    displayName: 'Yarn check'

  - script: |
      node concurrent-tests.js
    displayName: 'Run tests'
