pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run bootstrap
  displayName: 'Lerna bootstrap'
  
- script: |
    npm test
  displayName: 'Run tests'
