packages:
  - packages/*
  - bench/*
  - crates/*/js
  - turbopack/crates/*/js
  - turbopack/crates/turbopack-tests/tests/execution
  - turbopack/packages/*
catalog:
  '@actions/core': 1.10.1
  '@ampproject/toolbox-optimizer': 2.8.3
  '@ast-grep/cli': 0.25.6
  '@babel/code-frame': 7.22.5
  '@babel/core': 7.22.5
  '@babel/eslint-parser': 7.22.5
  '@babel/parser': 7.22.5
  '@babel/plugin-proposal-class-properties': 7.18.6
  '@babel/plugin-proposal-export-namespace-from': 7.18.9
  '@babel/plugin-proposal-numeric-separator': 7.18.6
  '@babel/plugin-proposal-object-rest-spread': 7.20.7
  '@babel/plugin-syntax-bigint': 7.8.3
  '@babel/plugin-syntax-dynamic-import': 7.8.3
  '@babel/plugin-syntax-import-attributes': 7.22.5
  '@babel/plugin-syntax-jsx': 7.22.5
  '@babel/plugin-transform-modules-commonjs': 7.22.5
  '@babel/plugin-transform-runtime': 7.22.5
  '@babel/preset-env': 7.22.5
  '@babel/preset-flow': 7.22.5
  '@babel/preset-react': 7.22.5
  '@babel/preset-typescript': 7.22.5
  '@babel/runtime': 7.22.5
  '@babel/traverse': 7.22.5
  '@capsizecss/metrics': 3.2.0
  '@datadog/datadog-api-client': ^1.13.0
  '@edge-runtime/cookies': 5.0.0
  '@edge-runtime/jest-environment': 3.0.0
  '@edge-runtime/ponyfill': 3.0.0
  '@edge-runtime/primitives': 5.0.0
  '@emotion/cache': 11.11.0
  '@emotion/react': 11.11.1
  '@fullhuman/postcss-purgecss': 1.3.0
  '@hapi/accept': 5.0.2
  '@jest/transform': 29.5.0
  '@jest/types': 29.5.0
  '@mantine/core': ^7.10.1
  '@mdx-js/loader': 2.2.1
  '@mdx-js/react': 2.2.1
  '@mswjs/interceptors': 0.23.0
  '@napi-rs/cli': 2.18.0
  '@napi-rs/triples': 1.2.0
  '@next/env': 15.0.0-canary.115
  '@next/eslint-plugin-next': 15.0.0-canary.115
  '@next/font': 15.0.0-canary.115
  '@next/polyfill-module': 15.0.0-canary.115
  '@next/polyfill-nomodule': 15.0.0-canary.115
  '@next/react-refresh-utils': 15.0.0-canary.115
  '@next/swc': 15.0.0-canary.115
  '@picocss/pico': 1.5.10
  '@playwright/test': 1.41.2
  '@replayio/jest': 27.2.35
  '@replayio/playwright': 1.1.8
  '@replayio/replay': 0.20.1
  '@rushstack/eslint-patch': ^1.3.3
  '@svgr/webpack': 5.5.0
  '@swc/cli': 0.1.55
  '@swc/counter': 0.1.3
  '@swc/helpers': 0.5.12
  '@swc/types': 0.1.7
  '@szmarczak/http-timer': 5.0.1
  '@taskr/clear': 1.1.0
  '@taskr/esnext': 1.1.0
  '@testing-library/jest-dom': 6.1.2
  '@testing-library/react': ^15.0.5
  '@types/amphtml-validator': 1.0.0
  '@types/async-retry': 1.4.2
  '@types/babel__code-frame': 7.0.2
  '@types/babel__core': 7.1.12
  '@types/babel__generator': 7.6.2
  '@types/babel__template': 7.4.0
  '@types/babel__traverse': 7.11.0
  '@types/busboy': 1.5.3
  '@types/bytes': 3.1.1
  '@types/cheerio': 0.22.16
  '@types/ci-info': 2.0.0
  '@types/compression': 0.0.36
  '@types/content-disposition': 0.5.4
  '@types/content-type': 1.1.3
  '@types/cookie': 0.3.3
  '@types/cross-spawn': 6.0.0
  '@types/debug': 4.1.5
  '@types/express-serve-static-core': 4.17.33
  '@types/fontkit': 2.0.0
  '@types/fresh': 0.5.0
  '@types/fs-extra': 8.1.0
  '@types/glob': 7.1.1
  '@types/graceful-fs': 4.1.9
  '@types/html-validator': 5.0.3
  '@types/http-proxy': 1.17.3
  '@types/inquirer': ^9.0.3
  '@types/jest': 29.5.5
  '@types/jscodeshift': 0.11.0
  '@types/jsonwebtoken': 9.0.0
  '@types/loader-runner': ^2.2.4
  '@types/lodash': 4.14.198
  '@types/lodash.curry': 4.1.6
  '@types/lru-cache': 5.1.0
  '@types/minimist': ^1.2.2
  '@types/node-fetch': 2.6.1
  '@types/path-to-regexp': 1.7.0
  '@types/picomatch': 2.3.3
  '@types/platform': 1.3.4
  '@types/prompts': 2.4.2
  '@types/react-is': 18.2.4
  '@types/relay-runtime': 14.1.13
  '@types/semver': 7.3.1
  '@types/send': 0.14.4
  '@types/shell-quote': 1.7.1
  '@types/split2': ^4.2.0
  '@types/string-hash': 1.1.1
  '@types/text-table': 0.2.1
  '@types/trusted-types': 2.0.3
  '@types/ua-parser-js': 0.7.36
  '@types/validate-npm-package-name': 4.0.2
  '@types/webpack': ^5.28.0
  '@types/webpack-sources1': npm:@types/webpack-sources@0.1.5
  '@types/ws': 8.2.0
  '@vercel/fetch': 6.1.1
  '@vercel/nft': 0.27.1
  '@vercel/og': 0.6.2
  '@vercel/turbopack-ecmascript-runtime': '*'
  abort-controller: 3.0.0
  acorn: 8.11.3
  alex: 9.1.0
  amphtml-validator: 1.0.35
  anser: 1.4.9
  arg: 4.1.0
  asciichart: 1.5.25
  assert: 2.0.0
  babel-plugin-react-compiler: 0.0.0-experimental-c23de8d-20240515
  babel-plugin-transform-define: 2.0.0
  babel-plugin-transform-react-remove-prop-types: 0.4.24
  browserify-zlib: 0.2.0
  browserslist: 4.22.2
  buffer: 5.6.0
  busboy: 1.6.0
  bytes: 3.1.1
  caniuse-lite: ^1.0.30001579
  ci-info: 4.0.0
  cli-select: 1.1.2
  client-only: 0.0.1
  comment-json: 3.0.3
  compression: 1.7.4
  constants-browserify: 1.0.0
  content-disposition: 0.5.3
  content-type: 1.0.4
  cookie: 0.4.1
  core-js: 3.6.5
  cors: 2.8.5
  coveralls: 3.0.3
  critters: 0.0.6
  crypto-browserify: 3.12.0
  css.escape: 1.5.1
  cssnano-preset-default: 5.2.14
  data-uri-to-buffer: 3.0.1
  dd-trace: 4.12.0
  debug: 4.1.1
  devalue: 2.0.1
  domain-browser: 4.19.0
  dotenv-expand: 10.0.0
  downsample-lttb: 0.0.1
  edge-runtime: 3.0.0
  es5-ext: 0.10.53
  escape-string-regexp: 2.0.0
  eslint: 8.56.0
  eslint-formatter-codeframe: 7.32.1
  eslint-import-resolver-node: ^0.3.6
  eslint-import-resolver-typescript: ^3.5.2
  eslint-plugin-eslint-plugin: 5.2.1
  eslint-plugin-jest: 27.6.3
  eslint-plugin-jsdoc: 48.0.4
  eslint-plugin-jsx-a11y: ^6.7.1
  event-stream: 4.0.1
  events: 3.3.0
  expect: 29.5.0
  expect-type: 0.14.2
  express: 4.17.0
  faker: 5.5.3
  fast-glob: 3.3.1
  faunadb: 2.6.1
  find-up: 4.1.0
  firebase: 7.14.5
  flat: 5.0.2
  fontkit: 2.0.2
  fresh: 0.5.2
  get-port: 5.1.1
  get-port-please: 3.1.1
  globby: 11.0.1
  graceful-fs: ^4.2.11
  gzip-size: 5.1.1
  html-validator: 5.1.18
  http-proxy: 1.18.1
  http-proxy-agent: 5.0.0
  https-browserify: 1.0.0
  https-proxy-agent: 5.0.1
  husky: 9.0.11
  icss-utils: 5.1.0
  ignore-loader: 0.1.2
  image-size: 1.1.1
  is-animated: 2.0.2
  is-docker: 2.0.0
  is-git-clean: 1.1.0
  is-wsl: 2.2.0
  isomorphic-unfetch: 3.0.0
  jest: 29.7.0
  jest-circus: 29.5.0
  jest-environment-jsdom: 29.7.0
  jest-extended: 4.0.2
  jest-junit: 16.0.0
  jest-worker: 27.5.1
  jscodeshift: 0.13.1
  json5: 2.2.3
  jsonwebtoken: 9.0.0
  kleur: ^4.1.0
  ky: 0.19.1
  ky-universal: 0.6.0
  lerna: 4.0.0
  lint-staged: 15.2.2
  listr2: 5.0.8
  loader-utils2: npm:loader-utils@2.0.0
  loader-utils3: npm:loader-utils@3.1.3
  lodash: 4.17.20
  lodash-es: ^4.17.21
  lodash.curry: 4.1.1
  lost: 8.3.1
  lru-cache: 5.1.1
  lucide-react: ^0.383.0
  meow: 7.0.1
  mermaid: ^10.9.1
  microbundle: 0.15.0
  mini-css-extract-plugin: 2.4.4
  minimatch: 3.0.4
  minimist: ^1.2.8
  moment: ^2.24.0
  msw: 2.3.0
  native-url: 0.3.4
  neo-async: 2.6.1
  next: 15.0.0-canary.115
  node-fetch: 2.6.7
  node-html-parser: 5.3.3
  node-plop: 0.31.1
  nprogress: 0.2.0
  object-assign: 4.1.1
  octokit: 3.1.0
  ora: 4.0.4
  os-browserify: 0.3.0
  outdent: 0.8.0
  p-limit: 3.1.0
  path-browserify: 1.0.1
  path-to-regexp: 6.1.0
  picomatch: 4.0.1
  pidusage-tree: ^2.0.5
  pixrem: 5.0.0
  platform: 1.3.6
  playwright: 1.41.2
  postcss: 8.4.31
  postcss-flexbugs-fixes: 5.0.2
  postcss-modules-extract-imports: 3.0.0
  postcss-modules-local-by-default: 4.0.4
  postcss-modules-scope: 3.0.0
  postcss-modules-values: 4.0.0
  postcss-nested: 4.2.1
  postcss-preset-env: 7.4.3
  postcss-pseudoelements: 5.0.0
  postcss-safe-parser: 6.0.0
  postcss-scss: 4.0.3
  postcss-short-size: 4.0.0
  postcss-trolling: 0.1.7
  postcss-value-parser: 4.2.0
  prettier-2: npm:prettier@^2
  prettier-plugin-tailwindcss: 0.6.2
  pretty-bytes: 5.3.0
  process: 0.11.10
  prompts: 2.4.2
  punycode: 2.1.1
  querystring-es3: 0.2.1
  random-seed: 0.3.0
  raw-body: 2.4.1
  react-refresh: 0.12.0
  react-ssr-prepass: 1.0.8
  react-test-renderer: 18.2.0
  react-virtualized: 9.22.3
  recursive-copy: 2.0.11
  regenerator-runtime: 0.13.4
  relay-compiler: 13.0.2
  relay-runtime: 13.0.2
  release: 6.3.1
  request-promise-core: 1.1.2
  resolve-from: 5.0.0
  rimraf: ^3.0.2
  sass: 1.54.0
  sass-loader: 12.6.0
  satori: 0.10.9
  scheduler-builtin: npm:scheduler@0.25.0-rc-187dd6a7-20240806
  scheduler-experimental-builtin: npm:scheduler@0.0.0-experimental-187dd6a7-20240806
  schema-utils2: npm:schema-utils@2.7.1
  schema-utils3: npm:schema-utils@3.0.0
  seedrandom: 3.0.5
  send: 0.17.1
  server-only: 0.0.1
  setimmediate: 1.0.5
  sharp: ^0.33.4
  shell-quote: 1.7.3
  source-map-loader: 5.0.0
  source-map08: npm:source-map@0.8.0-beta.0
  split2: ^4.2.0
  stacktrace-parser: 0.1.10
  stream-browserify: 3.0.0
  stream-http: 3.1.1
  strict-event-emitter: 0.5.0
  string_decoder: 1.3.0
  string-hash: 1.1.3
  strip-ansi: 6.0.0
  styled-components: 6.0.0-rc.3
  styled-jsx-plugin-postcss: 3.0.2
  superstruct: 1.0.3
  swr: ^2.2.4
  tailwindcss: 3.2.7
  taskr: 1.1.0
  term-size: 3.0.2
  terser: 5.27.0
  terser-webpack-plugin: 5.3.9
  text-table: 0.2.0
  third-party-capital: 1.0.20
  timers-browserify: 2.0.12
  tsec: 0.2.1
  tty-browserify: 0.0.1
  turbo: 2.0.9
  typescript: 5.5.3
  ua-parser-js: 1.0.35
  unfetch: 4.2.0
  unistore: 3.4.1
  update-check: 1.5.4
  util: 0.12.4
  validate-npm-package-name: 5.0.1
  vm-browserify: 1.1.2
  wait-port: 0.2.2
  watchpack: 2.4.0
  web-vitals: 4.2.1
  webpack-sources1: npm:webpack-sources@1.4.3
  webpack-sources3: npm:webpack-sources@3.2.3
  webpack-stats-plugin: ^1.1.0
  whatwg-fetch: 3.0.0
  ws: 8.2.3
  yargs: 16.2.0
  zod: 3.22.3
