schema: lib/type-defs.graphqls
documents: '**/*.graphql'
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
config:
  withHooks: true
  reactApolloVersion: 3
respectGitIgnore: true
