[workspace]

members = [
  "crates/core",
  "crates/napi",
  "crates/wasm"
]

# https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev.package."*"]
opt-level = 2

[profile.release]
lto = true