name: Example Bug Report
description: Create a bug report for one of the Next.js examples
labels: 'type: example,template: bug'
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report for [one of the examples](https://github.com/vercel/next.js/tree/canary/examples)! Please fill out this form as completely as possible.
  - type: markdown
    attributes:
      value: If you leave out sections there is a high likelihood it will be moved to the GitHub Discussions ["Help" section](https://github.com/vercel/next.js/discussions/categories/help).
  - type: checkboxes
    attributes:
      label: Verify canary release
      description: '`next@canary` is the beta version of Next.js. It includes all features and fixes that are pending to land on the stable release line. Some issues might have already been fixed there, so please verify that your issue exists in Next.js canary releases (`npm install next@canary`) before opening a new bug report.'
      options:
        - label: I verified that the issue exists in Next.js canary release
          required: true
  - type: textarea
    attributes:
      label: Provide environment information
      description: Please run `next info` in the root directory of your project and paste the results. You might need to use `npx --no-install next info` if next is not in the current PATH.
    validations:
      required: false
  - type: input
    attributes:
      label: "What example does this report relate to? See a complete list in the [examples folder](https://github.com/vercel/next.js/tree/canary/examples). Note: Examples not in the exmples folder might be maintained by the example's library author. Check out their projects before opening the issue on Next.js"
      description: 'For example: with-styled-components'
    validations:
      required: true
  - type: input
    attributes:
      label: What browser are you using?
      description: 'For example: Chrome, Safari'
    validations:
      required: true
  - type: input
    attributes:
      label: How are you deploying your application?
      description: 'For example: next start, next export, Vercel, Other platform'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior, please provide a clear code snippets that always reproduces the issue or a GitHub repository. Screenshots can be provided in the issue body below.
    validations:
      required: true
  - type: markdown
    attributes:
      value: Before posting the issue go through the steps you've written down to make sure the steps provided are detailed and clear.
  - type: markdown
    attributes:
      value: Contributors should be able to follow the steps provided in order to reproduce the bug.
  - type: markdown
    attributes:
      value: Thanks in advance!
