name: 'Docs Request for an Update or Improvement'
description: A task to update or improve Next.js documentation
title: ''
labels:
  - 'area: documentation'
projects:
  - Documentation
body:
  - type: textarea
    attributes:
      label: What is the improvement or update you wish to see?
      description: 'Example: Id like to see more examples of how to use the `<Link>` component. Or, the <Link> component docs are missing information.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is there any context that might help us understand better?
      description: A clear description of any added context that might help us understand better.
    validations:
      required: true
  - type: input
    attributes:
      label: Does the docs page already exist? Please link to it?
      description: 'Example: https://nextjs.org/docs/api-reference/next/link'
    validations:
      required: false
