blank_issues_enabled: false
contact_links:
  - name: Ask a Next.js question or discuss a Next.js topic
    url: https://github.com/vercel/next.js/discussions
    about: Ask questions and/or discuss with other Next.js users in Discussions(https://github.com/vercel/next.js/discussions).
  - name: Feature or Documentation request
    url: https://github.com/vercel/next.js/discussions/new?category=ideas
    about: Open a feature or documentation reuquest in Discussions(https://github.com/vercel/next.js/discussions/new?category=ideas).
  - name: Next.js Learn course
    url: https://github.com/vercel/next-learn/issues/new
    about: Next.js Learn course-related issues should be reported in this repository instead.
