ชื่อ : 'ปิดปัญหาเก่า'
บน :
  กำหนดการ :
  - cron : ' 0 * * * * '

งาน :
  ค้าง :
    รันออน : ubuntu-latest
    ขั้นตอน :
    - การ ใช้งาน : actions/stale@v6
      ด้วย :
        โทเค็น repo : ${{secrets.YARNBOT_TOKEN}}

        stale-issue-message : |
          สวัสดี! 👋
          ปัญหานี้ดูเก่าและไม่มีป้ายกำกับ "ทำซ้ำได้" ซึ่งหมายความว่าคุณไม่ได้จัดเตรียมการทำซ้ำที่ใช้งานได้โดยใช้ [Sherlock](https://yarnpkg.com/advanced/sherlock) ด้วยเหตุนี้ จะปิดในอีกสองสามวันเว้นแต่ผู้ดูแลจะรับรองอย่างชัดแจ้งหรือคุณแก้ไขโพสต์แรกของคุณให้มีการทำสำเนาอย่างเป็นทางการ (คุณสามารถใช้ [สนามเด็กเล่น](http://yarnpkg.com/playground) สำหรับการที่).
          โปรดทราบว่าเราต้องการการทำซ้ำ Sherlock สำหรับปัญหาที่มีอายุการใช้งานยาวนาน (แทนที่จะเป็นที่เก็บ git แบบสแตนด์อโลนหรือที่คล้ายกัน) เนื่องจากเราเป็นทีมขนาดเล็ก Sherlock ช่วยให้เราสามารถตรวจสอบข้อบกพร่องที่ยังคงส่งผลกระทบต่อมาสเตอร์แบรนช์ ณ จุดใดก็ตาม และลดจำนวนโค้ดที่เราต้องเรียกใช้บนเครื่องของเราเอง มันช่วยให้เราช่วยคุณได้! 😃
          หากคุณ *ไม่สามารถ* สร้างจุดบกพร่องบน Sherlock ได้ (เช่น เนื่องจากเป็นปัญหาสำหรับ Windows เท่านั้น) ผู้ดูแลจะต้องเพิ่มป้ายกำกับ "สนับสนุน" ด้วยตนเอง ขอขอบคุณที่ช่วยเราวิเคราะห์พื้นที่เก็บข้อมูลของเรา 🌟
        remove-stale- when-updated : false

        วันก่อนหมดอายุ : 30
        วันก่อนปิด : 5

        ป้ายกำกับเท่านั้น : ' bug '

        stale-issue-label : 'เก่า'
        exempt-issue-labels : 'ทำซ้ำได้ ยึดถือ ฉบับแรกที่ดี ต้องการความช่วยเหลือ'

    - การ ใช้งาน : actions/stale@v6
      ด้วย :
        โทเค็น repo : ${{secrets.YARNBOT_TOKEN}}

        stale-issue-message : |
          สวัสดี! 👋
          ดูเหมือนว่าปัญหานี้จะถูกทำเครื่องหมายว่าน่าจะได้รับการแก้ไขแล้ว หรือไม่มีข้อมูลสำคัญที่ขัดขวางความคืบหน้า ด้วยเหตุนี้ จะปิดในอีกสองสามวันเว้นแต่ผู้ดูแลจะรับรองอย่างชัดแจ้ง
        remove-stale- when-updated : true

        วันก่อนหมดอายุ : 30
        วันก่อนปิด : 5

        only-labels : 'กำลังรอข้อเสนอแนะ'

        stale-issue-label : 'เก่า'
