[package]
authors = ["next.js developers"]
edition = "2018"
license = "Apache-2.0"
name = "styled_jsx"
repository = "https://github.com/vercel/next.js.git"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easy-error = "1.0.0"
swc_common = {version = "0.17.18", features = ["concurrent", "sourcemap"]}
swc_css = "0.103.0"
swc_css_prefixer = "0.99.3"
swc_ecmascript = {version = "0.140.0", features = ["parser", "minifier", "utils", "visit"]}
tracing = {version = "0.1.28"}

[dev-dependencies]
swc_ecma_transforms_testing = "0.75.0"
testing = "0.19.1"
