version: '3'

services:
  # Next.js JavaScript app
  next-js-app:
    container_name: next-js-app
    build:
      context: ./next-js-app
      dockerfile: prod-without-multistage.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000:3000 # host:container
    networks:
      - my_network

  # Next.js TypeScript app
  next-ts-app:
    container_name: next-ts-app
    build:
      context: ./next-ts-app
      dockerfile: prod-without-multistage.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3002:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a bridge network, which allows containers to communicate with each other,
# by using their container name as a hostname
networks:
  my_network:
    external: true
