version: '3'

services:
  # Next.js app #1
  next-1:
    container_name: next-1
    build:
      context: ./next-1
      dockerfile: dev.Dockerfile
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    # Sync local changes with container for Hot Reloading with Next.js
    # It's not necessary to sync the `.next` and `node_modules` directories
    volumes:
      - ./next-1/src:/app/src
      - ./next-1/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  # Next.js app #2
  next-2:
    container_name: next-2
    build:
      context: ./next-2
      dockerfile: dev.Dockerfile
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    volumes:
      - ./next-2/src:/app/src
      - ./next-2/public:/app/public
    restart: always
    ports:
      - 3002:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a bridge network, which allows containers to communicate with each other,
# by using their container name as a hostname
networks:
  my_network:
    external: true
