[package]
edition = "2018"
name = "next-swc"
version = "0.0.0"
publish = false

[features]
plugin = ["swc_core/plugin_transform_host_native"]

[dependencies]
chrono = "0.4"
easy-error = "1.0.0"
either = "1"
fxhash = "0.2.1"
once_cell = "1.13.0"
pathdiff = "0.2.0"
regex = "1.5"
serde = "1"
serde_json = "1"
swc_emotion = { git = "https://github.com/kwonoj/plugins.git", rev = "536b025152ef3622d0e09c730ad95c20dab9265d" }
styled_jsx = { git = "https://github.com/kwonoj/plugins.git", rev = "536b025152ef3622d0e09c730ad95c20dab9265d" }
styled_components = { git = "https://github.com/kwonoj/plugins.git", rev = "536b025152ef3622d0e09c730ad95c20dab9265d" }
modularize_imports = { git = "https://github.com/kwonoj/plugins.git", rev = "536b025152ef3622d0e09c730ad95c20dab9265d" }
tracing = { version = "0.1.37", features = ["release_max_level_info"] }

swc_core = { features = [
  "common_concurrent",
  "ecma_ast",
  "ecma_visit",
  "ecma_loader_node",
  "ecma_loader_lru",
  "ecma_utils",
  "ecma_minifier",
  "ecma_transforms",
  "__ecma_transforms",
  "ecma_transforms_react",
  "ecma_transforms_typescript",
  "ecma_transforms_optimization",
  "ecma_parser",
  "ecma_parser_typescript",
  "cached",
  "base",
], git = "https://github.com/swc-project/swc.git", rev = "171733e8bb26e0ea7b88cba4279fecd243d0a440" }

[dev-dependencies]
swc_core = { features = [
  "testing_transform",
], git = "https://github.com/swc-project/swc.git", rev = "171733e8bb26e0ea7b88cba4279fecd243d0a440" }
testing = { git = "https://github.com/swc-project/swc.git", rev = "171733e8bb26e0ea7b88cba4279fecd243d0a440" }
walkdir = "2.3.2"
