[package]
edition = "2018"
name = "next-swc"
version = "0.0.0"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
plugin = [
  "swc_core/plugin_transform_host_native"
]

[dependencies]
chrono = "0.4"
easy-error = "1.0.0"
either = "1"
fxhash = "0.2.1"
once_cell = "1.13.0"
pathdiff = "0.2.0"
regex = "1.5"
serde = "1"
serde_json = "1"
swc_emotion = {path="../emotion"}
styled_components = {path="../styled_components"}
styled_jsx = {path="../styled_jsx"}
modularize_imports = {path="../modularize_imports"}
tracing = { version = "0.1.32", features = ["release_max_level_info"] }

swc_core = { version = "0.11.7", features = [
  "common_concurrent",
  "ast",
  "visit",
  "loader_node",
  "loader_lru",
  "utils",
  "minifier",
  "transforms",
  "transforms_react",
  "transforms_typescript",
  "parser",
  "parser_typescript",
  "cached",
  "base" # concurrent?
] }

[dev-dependencies]
swc_core = { version = "0.11.7", features = ["testing_transform"]}
testing = "0.29.4"
walkdir = "2.3.2"
