on:
  push:
    branches: [canary]
  pull_request:
    types: [opened, synchronize]

name: Build, test, and maybe deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'repo'

      - run: cd repo && yarn install --frozen-lockfile --check-files
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - uses: actions/cache@v1
        id: cache-build
        with:
          path: repo
          key: ${{ github.sha }}

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: repo
          key: ${{ github.sha }}

      - run: cd repo && yarn lint

  testAll:
    name: Test All 1/6
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: repo
          key: ${{ github.sha }}

      - run: cd repo && node run-tests.js --timings -g 1/6 -c 3
        env:
          NEXT_TELEMETRY_DISABLED: 1
          HEADLESS: true

  testFirefox:
    name: Test Firefox (production)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: repo
          key: ${{ github.sha }}

      - run: cd repo && yarn testfirefox --forceExit test/integration/production/
        env:
          NEXT_TELEMETRY_DISABLED: 1
          HEADLESS: true

  testSafari:
    name: Test Safari (production)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'canary'
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: repo
          key: ${{ github.sha }}

      - run: cd repo && yarn testfirefox --forceExit test/integration/production/
        env:
          NEXT_TELEMETRY_DISABLED: 1
