name: check-examples
on: [push, pull_request]
jobs:
  check-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install moreutils
        run: sudo apt install moreutils
      - name: Check examples
        run: ./scripts/check-examples.sh
