name: SH Runner
on:
  pull_request:
env:
  ACTIONS_RUNNER_HOOK_JOB_STARTED: test
jobs:
  unit-tests:
    runs-on: [self-hosted, windows, x64]
    steps:
    - uses: actions/checkout@v3
    - name: unit-tests
      continue-on-error: true
      run: |
        echo "Hello?"
