name: SH Runner
on:
  pull_request:
jobs:
  unit-tests:
    runs-on: [self-hosted, linux, x64, metal]
    steps:
    - uses: actions/checkout@v3
    - name: unit-tests
      continue-on-error: true
      run: |
        echo "Hello?"
