name: Label issues - custom

on:
  issues:
    types: [labeled]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/issue-auto-label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
