name: On issue comment

on:
  issue_comment:
    types: [created]

jobs:
  needs-triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/needs-triage
      - uses: ./.github/actions/issue-on-comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
