name: Notify about the top 15 issues/PRs/feature requests (most reacted) in the last 90 days

on:
  schedule:
    - cron: '0 13 * * 1' # Every Monday at 1PM UTC (9AM EST)
  workflow_dispatch:
  pull_request:

jobs:
  run:
    if: github.repository_owner == 'vercel'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: corepack enable
      - name: 'Issues: Send notification to Slack'
        run: node ./.github/actions/next-repo-info/dist/issues/index.mjs
        continue-on-error: true
      - name: 'PRs: Send notification to Slack'
        run: node ./.github/actions/next-repo-info/dist/prs/index.mjs
        continue-on-error: true
      - name: 'Feature requests: Send notification to Slack'
        run: node ./.github/actions/next-repo-info/dist/feature-requests/index.mjs
        continue-on-error: true
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
