on:
  pull_request:
    types: [opened, synchronize]

name: Generate Pull Request Stats

jobs:
  stats:
    name: PR Stats
    runs-on: ubuntu-latest
    steps:
      - run: echo ::set-output name=DOCS_CHANGE::$(node skip-docs-change.js echo 'non-docs')
        id: docs-change
      - uses: actions/checkout@v2
        if: ${{ steps.docs-change.outputs.DOCS_CHANGE == 'non-docs' }}
      - uses: ./.github/actions/next-stats-action
        if: ${{ steps.docs-change.outputs.DOCS_CHANGE == 'non-docs' }}
