on:
  push:
    branches: [canary]
  pull_request:
    types: [opened, synchronize]

name: Generate pull request stats

jobs:
  prStats:
    name: PR Stats
    runs-on: ubuntu-latest
    steps:
      - name: PR Stats
        uses: zeit/next-stats-action@master
        env:
          COMMENT_ENDPOINT: https://next-stats.jjsweb.site/api/comment
