on:
  pull_request:
    types: [opened, synchronize]

name: Generate Pull Request Stats

jobs:
  prStats:
    runs-on: ubuntu-latest
    steps:
      - uses: zeit/next-stats-action@master
        env:
          COMMENT_ENDPOINT: https://next-stats.jjsweb.site/api/comment
