on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0,12 * * *'

name: Test react@experimental

jobs:
  testAll:
    name: Test All
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
      HEADLESS: true
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2, 3, 4, 5, 6]
    steps:
      - uses: actions/checkout@v2

      - run: yarn install --frozen-lockfile --check-files

      - run: yarn upgrade react@experimental react-dom@experimental -W --dev

      # TODO: remove after we fix watchpack watching too much
      - run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - run: node run-tests.js --timings -g ${{ matrix.group }}/6 -c 3
